### PR TITLE
BUG: debug new env

### PR DESCRIPTION
**Pull request by st3107**

### CODE REVIEW

**Comment by st3107** [comment]
Hi @sbillinge . I debug the code so that it can work with the latest dependencies. The CI test and build passed on my fork. It doesn't show here probably because of some settings of travis which I don't have the access to.

Could you grant me the maintainer rights of this repo. I would like to have the right to merge PR.

**Comment by st3107** [comment]
Hi @CJ-Wright . I encounter several XFAIL when I run the test and they all shows this traceback. It seems like a pytest version problem. I wonder if it is OK to merge with the XFAIL.

```
Process finished with exit code 0
XFAIL                             [100%]
cls = <class '_pytest.runner.CallInfo'>
func = <function call_runtest_hook.<locals>.<lambda> at 0x12619adc0>
when = 'setup'
reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)

    @classmethod
    def from_call(cls, func, when, reraise=None) -> "CallInfo":
        #: context of invocation: one of "setup", "call",
        #: "teardown", "memocollect"
        start = time()
        excinfo = None
        try:
>           result = func()

/anaconda3/envs/shed/lib/python3.8/site-packages/_pytest/runner.py:244: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/anaconda3/envs/shed/lib/python3.8/site-packages/_pytest/runner.py:217: in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
/anaconda3/envs/shed/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
/anaconda3/envs/shed/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/anaconda3/envs/shed/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
/anaconda3/envs/shed/lib/python3.8/site-packages/_pytest/skipping.py:93: in pytest_runtest_setup
    check_xfail_no_run(item)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

item = <Function test_replay_dummy_node>

    def check_xfail_no_run(item):
        """check xfail(run=False)"""
        if not item.config.option.runxfail:
            evalxfail = item._store[evalxfail_key]
            if evalxfail.istrue():
                if not evalxfail.get("run", True):
>                   xfail("[NOTRUN] " + evalxfail.getexplanation())
E                   _pytest.outcomes.XFailed: [NOTRUN] yield tests were removed in pytest 4.0 - test_replay_dummy_node will be ignored

/anaconda3/envs/shed/lib/python3.8/site-packages/_pytest/skipping.py:111: XFailed
```

**Comment by CJ-Wright** [comment]
I'd prefer if the issue was fixed.

**Comment by sbillinge** [comment]
@st3107 if you make a PR with the travis config changes you need I can merge it.  We shouldn't merge this unless it is passing.

**Comment by st3107** [comment]
I think it is not because of the configuration file but the setting of
Travis of this repo. I need the admin rights to look at the setting.

**Comment by sbillinge** [comment]
OK @st3107 you should have access now.

**Pull request merged**
